In [ ]:
import numpy as np

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
import numpy as np
x = np.arange(4, dtype=np.int64)
y = np.full_like(x, 1)
print(y)

[1 1 1 1]


Q2 Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [ ]:
import numpy as np

ar = np.array([[1, 2], [3, 4]])
m = np.asmatrix(ar)
print(m)

[[1 2]
 [3 4]]


Q3 Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [ ]:
import numpy as np
np.arange(3,10.1,7/49)


array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

Q4 Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [ ]:
import numpy as np

ar = np.array([[1, 2, 3], [4, 5, 6]])

newar = ar.reshape(-1,order='F')
print(newar)


[1 4 2 5 3 6]


Q5 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
import numpy as np;
ar =np.array([1,2,3,4,5,6,7,8,9])
newarr = np.array_split(ar,[4,6])
print(newarr[0],newarr[1],newarr[2])

[1 2 3 4] [5 6] [7 8 9]


 Q6 Compute the inverse and primary diagnol sum of x=[[1,2],[3,4]]

In [ ]:
import numpy as np
A=np.array([[1,2],[3,4]])
sum=A[0][0]+A[1][1]
det=-2
x=A[1][1]
A[1][1]=A[0][0]
A[0][0]=x
A[0][1]*=-1
A[1][0]*=-1
print(A/det,sum)

[[-2.   1. ]
 [ 1.5 -0.5]] 5


Q7 Sort x along the second axis. x = [[1,4],[3,1]]

In [ ]:
import numpy as np
ar=np.array([[1,4],[3,1]])
print(np.sort(ar,axis=1))

[[1 4]
 [1 3]]


Q8 Get the indices that would sort x(as above) along the second axis.

In [ ]:
import numpy as np
ar=np.array([[1,4],[3,1]])
np.argsort(ar,axis=1)

array([[0, 1],
       [1, 0]])

Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
import numpy as np;
x = np.random.randint(10,size=(2,5))
minn=np.amin(x,axis=1)
minni=np.argmin(x,axis=1)

maxx=np.amax(x,axis=1)
maxxi=np.argmax(x,axis=1)

print(maxx,maxxi)
print(minn,minni)

[9 9] [3 3]
[0 1] [0 2]


Run the following load command to get the 2-Dim iris dataset. Do the following operations on it.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

Drop rows that contain a missing value. 

In [ ]:
import pandas as pd
mn = pd.DataFrame(iris_2d)
mn.isnull()

0      1      2      3
0    False  False  False  False
1    False  False  False  False
2    False  False  False  False
3    False  False  False  False
4    False  False  False  False
..     ...    ...    ...    ...
145  False  False  False  False
146  False  False  False  False
147  False  False  False  False
148  False  False  False  False
149  False  False  False  False

[150 rows x 4 columns]

Find the correlation between first two columns.

In [ ]:
mn[0].corr(mn[1])

-0.10936924995064937

Find the mean,median and standard deviation of column 3.

In [ ]:
meann=mn[3].mean()
mediann=mn[3].median()
st=mn[3].std()
print(meann,mediann,st)

1.1986666666666672 1.3 0.7631607417008414


Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

In [ ]:
import math
import pandas as pd
mn = pd.DataFrame(iris_2d)
mn.insert(4,4,mn[0]*mn[0]*mn[2]*math.pi/3)
print(mn[0],mn[2],mn[4])


0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: 0, Length: 150, dtype: float64 0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ... 
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: 2, Length: 150, dtype: float64 0       38.132652
1       35.200498
2       30.072372
3       33.238050
4       36.651914
          ...    
145    244.445230
146    207.816354
147    230.069302
148    217.373079
149    185.910028
Name: 4, Length: 150, dtype: float64


Run the following loaad command and solve the following questions

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Find the count of unique species.

In [ ]:
import pandas as pd
mnn=pd.DataFrame(iris)
mnn[4].nunique()

3

Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
Less than 3 –> ‘small’
3-5 –> ‘medium’
‘>=5 –> ‘large’

In [ ]:
petal_bin = np.digitize(iris_2d[:,2].astype("float"), [0,3,5,10])
map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_cat = [map[x] for x in petal_bin]
petal_cat[:4]


['small', 'small', 'small', 'small']

Find the most frequent value of petal length (3rd column) in iris dataset

In [ ]:
mnn[2].mode()

0    b'1.5'
dtype: object